# -*- mode: ruby -*-
# vi: set ft=ruby :

$post_up_msg = <<-MSG
------------------------------------------------------
Provision has done. Great! Now you can start working by URL:

Admin Panel -  http://127.0.0.1:8080/zabbix

Admin account: Admin
Password:      zabbix

------------------------------------------------------
MSG

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vagrant.plugins = "vagrant-reload"
  config.vm.hostname = "lab-zabbix.party.hard"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
  end
  config.vm.synced_folder "../provision/zabbix", "/vagrant"
  #Install epel repo
  config.vm.provision "shell",
    inline: "yum install -y epel-release"
  #Install Ansible
  config.vm.provision "shell",
    inline: "yum install -y ansible"
  #Install Zabbix with Ansible
  config.vm.provision "shell",
    inline: "ansible-playbook  /vagrant/zabbix.yml -i /vagrant/hosts"
  config.vm.provision :reload
  config.vm.post_up_message = $post_up_msg
end
