# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure("2") do |config|	
	config.vagrant.plugins = "vagrant-reload"
	config.vm.define "lab-dc1" do |subconfig|
		subconfig.vm.box = "gusztavvargadr/windows-server"
		subconfig.vm.hostname = "lab-dc1"
		subconfig.vm.provider :virtualbox do |vb|
			vb.gui = false
		end
		subconfig.vm.network "private_network", ip: "192.168.11.2", 
			virtualbox__intnet: true
		subconfig.winrm.username = "vagrant"
		subconfig.winrm.password = "vagrant"
		subconfig.winrm.transport = :plaintext
		subconfig.winrm.basic_auth_only = true
		#Install DSC Modules
		subconfig.vm.provision "shell",
			path: "..\\provision\\PreDSCInstall.ps1"
		#https://github.com/dsccommunity/ActiveDirectoryDsc
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCInstallDomain.ps1"
		#Restart VM to finish Active Directory Domain Services installation
		subconfig.vm.provision :reload
		#https://github.com/dsccommunity/xDhcpServer
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCInstallDHCP.ps1"
	end
	  
	config.vm.define "lab-rds1" do |subconfig|
		subconfig.vm.box = "gusztavvargadr/windows-server"
		subconfig.vm.hostname = "lab-rds1"
		subconfig.vm.provider :virtualbox do |vb|
			vb.gui = false
		end
		subconfig.vm.network "private_network", ip: "127.0.0.2", 
			auto_config: false,
			virtualbox__intnet: true
		subconfig.winrm.username = "vagrant"
		subconfig.winrm.password = "vagrant"
		subconfig.winrm.transport = :plaintext
		subconfig.winrm.basic_auth_only = true
		subconfig.vm.boot_timeout = 300
		subconfig.winrm.timeout = 300
		#subconfig.winrm.retry_limit = 60
		#subconfig.winrm.retry_delay = 20
		subconfig.vm.provision "shell",
			path: "..\\provision\\PreDSCInstall.ps1"
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCJoinDomain.ps1"
		subconfig.vm.provision :reload
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCInstallRDS.ps1"
		subconfig.vm.provision :reload
		#https://github.com/dsccommunity/xRemoteDesktopSessionHost
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCConfigureRDSDeployment.ps1"
		subconfig.vm.provision :reload
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCConfigureRDS.ps1"	
	end
	
	config.vm.define "lab-rdgw1" do |subconfig|
		subconfig.vm.box = "gusztavvargadr/windows-server"
		subconfig.vm.hostname = "lab-rdgw1"
		subconfig.vm.provider :virtualbox do |vb|
			vb.gui = false
		end
		subconfig.vm.network "private_network", ip: "127.0.0.2", 
			auto_config: false,
			virtualbox__intnet: true
		subconfig.vm.network "private_network", ip: "192.168.51.2", 
			virtualbox__intnet: true
		subconfig.winrm.username = "vagrant"
		subconfig.winrm.password = "vagrant"
		subconfig.winrm.transport = :plaintext
		subconfig.winrm.basic_auth_only = true
		subconfig.vm.boot_timeout = 300
		subconfig.winrm.timeout = 300	
		subconfig.vm.provision "shell",
			path: "..\\provision\\PreDSCInstall.ps1"
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCJoinDomain.ps1"
		subconfig.vm.provision :reload
		#https://github.com/dsccommunity/xRemoteDesktopSessionHost
		subconfig.vm.provision "shell",
			path: "..\\provision\\DSCConfigureRDSGateway.ps1"
	end
	
	config.vm.define "lab-client1" do |subconfig|
		subconfig.vm.box = "gusztavvargadr/windows-server"
		subconfig.vm.hostname = "lab-client1"
		subconfig.vm.provider :virtualbox do |vb|
			vb.gui = false
		end
		subconfig.vm.network "private_network", ip: "192.168.51.3", 
			virtualbox__intnet: true
		subconfig.winrm.retry_limit = 60
		subconfig.winrm.retry_delay = 20
	end
end